apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app2
  labels:
    app.kubernetes.io/name: web-app2
  name: web-app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: web-app2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web-app2
    spec:
      containers:
      - image: registry.home-k8s.lab/k8s/web-hook-api
        name: web-app2


---

apiVersion: v1
kind: Service
metadata:
  name: web-app2
  labels:
    app.kubernetes.io/name: web-app2
spec:
  selector:
    app.kubernetes.io/name: web-app2
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000
  type: LoadBalancer