apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
data:
  Corefile: |-
    .:53 {
        log
        errors
        health {
            lameduck 5s
        }
        ready
        etcd kube-dc-1.home.lab {
            stubzones
            path /skydns
            endpoint http://172.20.0.65:2379
        }
        cache 30
        loop
        reload
    }
