apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: myapp-nginx

  source:
    repoURL: https://github.com/djangoreactdev/kubernetes-ansible.git
    targetRevision: HEAD
    path: test-app
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp-nginx

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
